title: Men's Advance
fonts_url: https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Slab&family=Tangerine&display=swap
registration_due_date: January 28, 2022
links:
  - url: /
    label: home
  # - url: /speakers
  #   label: speakers
  # - url: /venue
  #   label: venue
speakers:
  - name: Doug Pittam
    avatar: /assets/images/doug_pittam.jpeg
    bio_short: Doug Pittam has been the senior pastor of the Nazarene church in SLO (San Luis Obispo) since 2006.
    bio_long: Doug has been married to Sondi (AKA woman of his dreams) for 34 years now, has three beautiful grown daughters, and one terribly bright &amp; handsome grandson! Doug enjoys playing in the “old man basketball league” (40 and over), and kayak fishing when the sharks aren’t biting. He and his church are learning what it means to daily live out I Peter 4:8 “Above all...love each other deeply”. Doug’s connection with the Central California District Church of the Nazarene stretches back since 1990&mdash;He served the district as former NYI Pres (four years), and locally he served in the Connecting Point Church (Turlock/Denair Naz.) as youth pastor and Care Ministry pastor for 16 years (1990-2006).
    url: /speakers#doug-pittam
